### PR TITLE
English Manual Fixes

### PR DESCRIPTION
**Pull request by vpathalam**
Hello iperov,

I have performed some English spelling and grammar fixes to the English version of the manual without changing any content. I will continue to perform more fixes in the future as I notice them. Great project - I hope you accept my changes!

### CODE REVIEW

**Comment by iperov** [comment]
how you will track the changes in russian version of manual?

**Comment by vpathalam** [comment]
Unfortunately I don't speak Russian or other languages, these changes are only meant to make the English version clearer and more understandable to read. It seems as though the English manual was previously created using google translate,  so as a native English speaker, I think this will help in terms of English grammar.

**Comment by iperov** [comment]
but you deleted translated english version
so how you will track the changes in future?

**Comment by vpathalam** [comment]
Got it, would it be better to keep both the translated version and this newer version in that case? Let me know what you think.

**Comment by iperov** [comment]
ok how you will track the changes between translated and your version?

**Comment by vpathalam** [comment]
I can make changes in a different font color if you think that would be useful. I'm open to other suggestions too!

**Comment by iperov** [comment]
I have no suggestions.

**Comment by vpathalam** [comment]
Ok, your choice whether to merge or not - I can certainly open another request without the translated version deleted. Let me know your thoughts either way.

**Comment by TooMuchFun** [comment]
@vpathalam 

Thanks for all the effort, this looks great. Though @iperov is right. This is a code repository and tracking changes is critical. It's also important that we let the author of the code maintain an "official" manual in their native language. Lots of people want to help but few know how to code or run the project from script. Those few of us who can code know ML theory enough to help out, and documentation is always a great way to help.

Might I suggest you try putting together an annotated Google Colab notebook focused on theory and development process? For example, few people know the theory behind all the how each SAE training or convert options. [Here is a fantastic example of a notebook detailing the process for a CycleGAN](https://colab.research.google.com/drive/1Enc-pKlP4Q3cimEBfcQv0B_6hUvjVL3o). That could be a great starting point

Another route you could go is to post your guide in one of the MrDeepFakes forums? There are already a couple English guides in there. Yours could be an improvement. There is plenty of room out there for un- or semi-official guides.

**Comment by vpathalam** [comment]
Thank you @TooMuchFun for the suggestions - I really appreciate it. I'll attempt to put together the Google Colab notebook you mentioned as I further my learning of the process as well. The feedback both of you provided is understandable, looking forward to making a contribution in any way I can!

**Comment by iperov** [comment]
@vpathalam

I suggest you to write a new english documentation from scratch, because I don't want to update russian doc anymore.
What you think ?

**Comment by iperov** [comment]
@vpathalam
you can design chapters and images as you want.

**Pull request closed without merging**
