### PR TITLE
Fix log_info/log_err printing with progress bars

### PR DESCRIPTION
**Pull request by Auroir**
**Issue**
While a TQDM progress bar is active using a standard 'print' will cause unpredicable output. In most cases this causes the progress bar to be duplicated/frozen next to the log message:
```
Running on CPU0.
Running on CPU1.
Converting:   0% 0/356 [00:00<?, ?it/s]no faces found for 00001.png, copying without faces
Converting:   0% 1/356 [00:00<00:02, 165.12it/s]no faces found for 00002.png, copying without faces
Converting:   1% 2/356 [00:00<00:01, 318.97it/s]no faces found for 00003.png, copying without faces
Converting:   1% 3/356 [00:00<00:01, 255.22it/s]no faces found for 00004.png, copying without faces
Converting:   1% 4/356 [00:00<00:01, 333.46it/s]no faces found for 00005.png, copying without faces
Converting:   1% 5/356 [00:00<00:01, 287.34it/s]no faces found for 00006.png, copying without faces
Converting:   2% 6/356 [00:00<00:01, 340.82it/s]no faces found for 00007.png, copying without faces
Converting:   2% 7/356 [00:00<00:01, 301.00it/s]no faces found for 00008.png, copying without faces
Converting:   2% 8/356 [00:00<00:01, 341.15it/s]no faces found for 00009.png, copying without faces
Converting:   3% 9/356 [00:00<00:01, 310.79it/s]no faces found for 00010.png, copying without faces
Converting:   3% 10/356 [00:00<00:01, 342.98it/s]no faces found for 00011.png, copying without faces
Converting:   3% 11/356 [00:00<00:01, 317.86it/s]no faces found for 00012.png, copying without faces
Converting:   3% 12/356 [00:00<00:00, 344.40it/s]no faces found for 00013.png, copying without faces
Converting:   4% 13/356 [00:00<00:01, 322.13it/s]no faces found for 00014.png, copying without faces
```
**Resolution**
This can be mitigated by changing `log_info` and `log_err` to be aware of the presence of a progress bar and use `tqdm.write()` instead of `print()` if one exists:
```
Running on CPU0.
Running on CPU1.
no faces found for 00001.png, copying without faces
no faces found for 00002.png, copying without faces
no faces found for 00003.png, copying without faces
no faces found for 00004.png, copying without faces
no faces found for 00005.png, copying without faces
...
no faces found for 00197.png, copying without faces
no faces found for 00198.png, copying without faces
no faces found for 00199.png, copying without faces
Converting:  57% 203/356 [00:01<00:01, 120.22it/s]
```
**Method**
For `log_info` if a pb is running `tqdm.write` is attempted, if it fails a normal print is used. Likewise with `log_err` except that the msg is prefixed by `self.error_log_line_prefix`, `/!\`, to denote increased severity.

`progress_bar_generator()` has been updated to set `self.pb_bar` like the `progress_bar()` function and then clean up when the generator expires. Without this the class is unaware of the running pb since `self.pb_bar` remains defaulted to `None`.

**Result**
This doesn't completely fix the problem, there is still a lot of normal `print()` calls that will need to be updated eventually to use these for printing.
```
Loading:   3% 30/1000 [00:00<00:03, 297.17it/s]No Valid PNG header
00100.png is not a dfl image file required for training
Loading:  13% 126/1000 [00:00<00:02, 374.53it/s]No Valid PNG header
00200.png is not a dfl image file required for training
Loading:  30% 296/1000 [00:00<00:01, 519.82it/s]No Valid PNG header
00300.png is not a dfl image file required for training
Loading:  38% 380/1000 [00:00<00:01, 586.20it/s]No Valid PNG header
00400.png is not a dfl image file required for training
```
`No Valid PNG header` has not been updated to use `log_info`, causes duplicate progress bars. `<X> is not a dfl image file required for training` does use `log_info` and prints correctly. A majority of the commonly seen messages are covered, so this is still very worthwhile from a UX perspective.

### CODE REVIEW

**Comment by iperov** [comment]
@Auroir what do you think about to become a main developer of DFL?

**Comment by Auroir** [comment]
Sure, if anything I'd like it so I can clear out answered issues. I know how much you love the issues :grin: Besides that and making a helpful wiki, right now I'm working on a few things. 

1. Porting my colab fixups into the tools, which have been my last patches. I still have an alpha layer fix (insert alpha for frames w/o faces), an aligned face sorting & validation scheme, and an improved result encoding workflow. 
2. Add a color-space option to model setup. I want feed samples in the LAB colorspace, I have a hunch that colors will transfer better this way. And avoiding a YUV<->RGB conversion would be nice when you have YUV JPG files. It should end up just being a flag like BGR shuffling is right now, assuming it turns out to be useful at all.
3. Enable PNG face extraction. It seems to work fine for me, is there a reason it's not enabled right now? 
4. Pre-processing for src faces. This needs PNG files else quality will be lost re-encoding a JPG. Some hue shifting and sharpening before training can help a bunch, especially in cases where dst/src are so dissimilar that color transfer doesn't look natural. Getting the colors half way there at the start helps.
5. Use masked images as a base for color transfer calculations. Currently the background colors leak onto the face since the entire image's colors are considered. 
6. Add rescaling method option for face extraction. When you extract from HD content linear/cubic methods aren't optimal. Switching to 'area' for >1080p content and 'lanczos4' for 1080-720p has helped my results. Both the landmark detection as well as result quality. 

Do you have a testing environment setup for Windows? My Colab and Linux setups are very easy to run trials on but I don't have Windows all scripted like those are.

**Comment by iperov** [comment]
install VMWare and windows 7 to test DFL in CPU mode.
I have set you Collaborator status. Feel free to make any changes in the repo, but test it in the windows please.

**Comment by iperov** [comment]
also currently I am working on interactive converter

**Comment by Auroir** [comment]
Sounds good, I'll get a couple of test workspaces up before I commit more.

**Comment by iperov** [comment]
@Auroir  about this PR.
I discovered a problem.
with that new logic
```
def log_info(self, msg, end='\n'):
        if self.pg_bar is not None:
            try: # Attempt print before the pb
                tqdm.write(msg)
                return
            except: 
                pass #Fallback to normal print upon failure
        print (msg, end=end)
```
sometimes
```
io.progress_bar_close()
```
can freeze process forever

**Comment by iperov** [comment]
tested with last version of tqdm. So I have to remove this pr from next release

**Comment by iperov** [comment]
new solution:
```
    def log_info(self, msg, end='\n'):
        if self.pg_bar is not None:
            print ("\n")
        print (msg, end=end)
```
is good enough and no freeze occur

**Pull request merged**
