### PR TITLE
PR for your 265x test model

### PR DESCRIPTION
**Pull request by andenixa**
Please include your 265x test model

### CODE REVIEW

**Comment by iperov** [comment]
post comparison vs 128 model at same epoch

**Comment by andenixa** [comment]
image

**Comment by iperov** [comment]
sry, 256 models sucks

**Comment by iperov** [comment]
also read mainpage about prs

**Comment by andenixa** [comment]
Sure. Well its your model. I just wanted you to add it to the repo since other had asked about it.

**Pull request closed without merging**
