### PR TITLE
DirectML plugin support in Tensorflow 2

### PR DESCRIPTION
**Pull request by brucehsu**
The existing version of DFL w/ DirectML is using a fork of Tensorflow 1.15 w/ DirectML support. The performance of this approach is less than ideal, as @iperov pointed out in this issue https://github.com/microsoft/DirectML/issues/108.

Since then, DirectML team has introduced a `tensorflow-directml-plugin`, which incorporates Pluggable Device API in Tensorflow 2, to provide an easier and faster way of leveraging DirectML in Tensorflow.

This PR introduces `tensorflow-directml-plugin` to DFL, without any significant changes to the existing models/scripts.

With brief benchmarks on my system (Ryzen 3600/Intel Arc A750 8GB/Windows 11/miniconda Python 3.7), I'm seeing
-  **45%** faster in Quick96 (`189ms`->`130ms`)
- **133%** faster in AMP (`2475ms`->`1060ms`)

If you want to try it yourself, you can follow the instructions below:
1. Download RTX30 series bundle of DFL
2. Download the executable here: https://github.com/brucehsu/DeepFaceLab/releases/tag/dml_plugin
3. Extract it to `_internal` directory of your DFL environment
4. Use DFL scripts as usual

### CODE REVIEW

**Comment by iperov** [comment]
cool but i don't plan to update dfl

**Comment by brucehsu** [comment]
> does this work on amd and if so could this work on deepfacelive or is it not needed.

It should since therotically every card that supports DirectX can leverage this. Someone already benchmarked this version with RTX 4090 and it yields generally better performance compread to the CUDA version: https://github.com/iperov/DeepFaceLab/issues/5628#issuecomment-1447594293

**Comment by Pickymarker** [comment]
> > does this work on amd and if so could this work on deepfacelive or is it not needed.
> 
> It should since therotically every card that supports DirectX can leverage this. Someone already benchmarked this version with RTX 4090 and it yields generally better performance compread to the CUDA version: [#5628 (comment)](https://github.com/iperov/DeepFaceLab/issues/5628#issuecomment-1447594293)

but what about using this in deepfacelive instead deepfacelab

**Comment by brucehsu** [comment]
Sorry, haven't really look into its codebase to make a comment :/
But if its the basic architecture and implementation isn't far away from DeepFaceLab then the probability you can leverage DirectML is high.

**Comment by Pickymarker** [comment]
yeah, that's what i was thinking just would need someone to implement it

**Comment by xzuyn** [comment]
does it matter if you use the 3000 series build or the directx12 build with this?

**Comment by Pickymarker** [comment]
use 3000 series version like it says on the direct ml support plugin github

**Comment by xzuyn** [comment]
> use 3000 series version like it says on the direct ml support plugin github

but does it change anything? i've been using it with the directx12 version for a while.

**Pull request closed without merging**
