### PR TITLE
rebase Linux work

### PR DESCRIPTION
**Pull request by xaiki**
this is a rebase of the latests source to https://github.com/lbfs/DeepFaceLab_Linux
it's been tested on Linux and should work flawlessly on windows too
a Dockerfile with nvidia/cuda is provided too.

### CODE REVIEW

**Comment by xaiki** [comment]
note that the script I use is a bit different from the ones provided:
```sh
model=DF

for v in $src $dst; do
        facedir=${v}_faces
        framesdir=${facedir}/raw_frames
        aligndir=${facedir}/aligned_faces
        debugdir=${facedir}/debug
        rm -rf ${facedir}
        mkdir -p ${framesdir} ${aligndir}
        python3.6 main.py videoed extract-video --input-file ${v} --output-dir ${framesdir}
        python3.6 main.py videoed denoise-image-sequence --input-dir ${framesdir}
        python3.6 main.py extract \
                  --input-dir ${framesdir} \
                  --output-dir ${aligndir} \
                  --multi-gpu \
                  --detector s3fd
        for i in black blur hist oneface face-dissim hist-dissim face-pitch face-yaw final; do
                python3.6 main.py sort --input-dir ${aligndir}  --by $i
        done
done

srcdir=${src}_faces/aligned_faces
dstdir=${dst}_faces/aligned_faces
modeldir=data/model/$(basename $src)-$(basename $dst)
mkdir -p ${modeldir}

python3.6 main.py train \
          --training-data-src-dir ${srcdir} \
          --training-data-dst-dir ${dstdir} \
          --model-dir ${modeldir} --model ${model}
```

**Comment by xaiki** [comment]
and this is the way I start the docker container to have X11 for viz:
```sh
docker run --runtime nvidia --net=host -v "$HOME/.Xauthority:/root/.Xauthority:rw" -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --privileged -it --rm -v $PWD:/srv -v $PWD/../data:/srv/data  -w /srv dfl bash
```

**Comment by TooMuchFun** [comment]
Linux is not a platform that iperov develops on. If he can't run your changes, he can't test. Will you continue maintaining these files and changes going forward, like he does? Will you field the inevitable Issues that come in related to this support, like he does?

Its also worth saying that this repo code runs great on Linux without any of this. Just run the requirements.txt and install the NVIDIA libs. I'm not entirely certain why the Linux fork exists anymore.

**Comment by xaiki** [comment]
There is one commit that fixes an encoding issue that prevented me from running this on linux.
Also the commits I ported add the Linux shell scripts and I have included a dockerfile to ease developement.
 
Basically if this gets merged it's only a matter of keeping on eye on linux breakage and submitting fixes

Sent with  FairEmail [https://email.faircode.eu/]  , an open source, privacy friendly email app for Android

**Comment by xaiki** [comment]
i've rebased and merged commits from @lbfs 
 - renamed `Development reset` to `Add linux scripts` and removed README.md modifications
 - dropped patches that were reseting themselves
 - dropped plaidml removal

i'm thinking of dropping the ubuntu/cuda installer as this series has a Dockerfile...

**Comment by xaiki** [comment]
So, the idea is to make this repo work for both linux and windows ?

when testing i actually had to download the provided build 7zip to get the windows scripts, maybe they should be added ? but actually, maybe they should be made into a simpler all-encompassing script ? I will post something like that here in a bit.

as for anaconda it bloats my machine, didn't work when i tried it (in a docker container) and really i'd rather have it all in a container. as it's been requested many times it's clearly something people want, why not give it to them (as it's done) do you really think that having 1 Dockerfile and 2 lines of doc will make this project unmanageable ?

the nnlib fix is, that in current master i have:
```
00000cd0  65 6e 76 69 72 6f 6e 5b  27 43 55 44 41 5f e2 80  |environ['CUDA_..|
00000ce0  8b 43 41 43 48 45 5f e2  80 8b 4d 41 58 53 49 5a  |.CACHE_...MAXSIZ|
```

these characters in nnlib/nnlib.py that were making `main.py convert` fail complaining about those chars.

**Comment by xaiki** [comment]
this could work as a 1shot do-all script

```sh
#!/bin/sh
set -e

function usage {
    echo ""
    echo "Usage: $0 [-modgplcDESNPh] src dst"
    echo "  -m : --model       model one of AVATAR,DEV_FANSEG,DEV_FUNIT,DEV_POSEEST,DF,H128,H64,LIAEF128,SAE,SAEHD"
    echo "  -o : --outfile     output filename, defaults to data/output.mp4"
    echo "  -d : --outdir      output directory, defaults to data/output/frames"
    echo "  -g : --gpu         gpu idx to use, defaults to -1"
    echo "  -p : --python      python binary to use, defaults to python3.6"
    echo "  -l : --lossless    create lossless videos"
    echo "  -c : --cpu-only    CPU only"
    echo "  -D : --debug       debug"
    echo "  -E : --noextract   Do not extract content"
    echo "  -S : --nosort      Do not sort extracted images"
    echo "  -N : --nodenoise   Do not denoise extracted images"
    echo "  -P : --nopreview   Do not show preview"
    echo ""
}

# Transform long options to short ones
for arg in "$@"; do
  shift
  case "$arg" in
    "--help")      set -- "$@" "-h" ;;
    "--model")     set -- "$@" "-m" ;;

    "--gpu")       set -- "$@" "-g" ;;
    "--outfile")   set -- "$@" "-o" ;;
    "--outdir")    set -- "$@" "-d" ;;
    "--python")    set -- "$@" "-p" ;;

    "--lossless")  set -- "$@" "-l" ;;
    "--cpu-only")  set -- "$@" "-c" ;;
    "--debug")     set -- "$@" "-D" ;;

    "--nosort")    set -- "$@" "-S" ;;
    "--noextract") set -- "$@" "-E" ;;
    "--nodenoise") set -- "$@" "-N" ;;
    "--nopreview") set -- "$@" "-P" ;;
    *)             set -- "$@" "$arg"
  esac
done

# Default behavior
model=DF;  gpu=-1;  dfl_python=python3.6;
outdir="./data/output/frames";   outfile="./data/output.mp4"
OPTIND=1
while getopts "hm:g:p:o:d:lcDESNP" opt; do
        case $opt in
                "h") usage; exit 1;;
                "m") model=$OPTARG;;

                "g") gpu=$OPTARG;;
                "o") outfile=$OPTARG;;
                "d") outdir=$OPTARG;;
                "p") python=$OPTARG;;

                "l") lossless=true;;
                "c") cpuonly=true;;
                "D") debug=true;;

                "E") noextract=true;;
                "S") nosort=true;;
                "N") nodenoise=true;;
                "P") nopreview=true;;
        esac
done
shift $(( $OPTIND - 1))

src=$1
dst=$2

test -z $src && echo "no src" && usage && exit 0
test -z $dst && echo "no dst" && usage && exit 0 

test -z $noextract && for v in $src $dst; do
        facedir=${v}_faces
        framesdir=${facedir}/raw_frames
        aligndir=${facedir}/aligned_faces
        debugdir=${facedir}/debug
        rm -rf ${facedir}
        mkdir -p ${framesdir} ${aligndir}
        # 2 and 3 extract png from video
        ${dfl_python} main.py videoed extract-video --input-file ${v} --output-dir ${framesdir}
        test -z $nodenoise && ${dfl_python} main.py videoed denoise-image-sequence --input-dir ${framesdir}
        ${dfl_python} main.py extract \
                  --input-dir ${framesdir} \
                  --output-dir ${aligndir} \
                  --multi-gpu \
                  --detector s3fd

        # 4 and 5 sort images
        test -z $nosort && for i in black blur hist oneface face-dissim hist-dissim face-pitch face-yaw final; do
                echo "sorting by $i"
                ${dfl_python} main.py sort --input-dir ${aligndir}  --by $i
                echo "go out and clear undesirable faces"
                read _
        done
done

srcdir=${src}_faces/aligned_faces
dstdir=${dst}_faces/aligned_faces
modeldir=data/model/$(basename $src)-$(basename $dst)
mkdir -p ${modeldir}
mkdir -p ${outdir}

extra_train_args=""
test -z $nopreview || extra_train_args="$extra_train_args --no-preview"
test -z $cpuonly   || extra_train_args="$extra_train_args --cpu-only"
test -z $debug     || extra_train_args="$extra_train_args --debug"

# 6 train
${dfl_python} main.py train \
          --training-data-src-dir ${srcdir} \
          --training-data-dst-dir ${dstdir} \
          --model-dir ${modeldir} --model ${model} \
          --force-gpu-idx ${gpu} \
          ${extra_train_args}

extra_convert_args=""
test -z $cpuonly   || extra_convert_args="$extra_convert_args --cpu-only"
test -z $debug     || extra_convert_args="$extra_convert_args --debug"

# 7 convert
${dfl_python} main.py convert \
              --input-dir ${srcdir} \
              --output-dir ${outdir} \
              --model-dir ${modeldir} \
              --model ${model} \
              ${extra_convert_args}

extra_videoed_args=""
test -z $lossless || extra_viedoed_args="$extra_videoed_args --lossless"

# 8 compose final video
${dfl_python} main.py videoed video-from-sequence \
    --input-dir ${outdir} \
    --output-file ${outfile} \
    --reference-file ${dst} \
    ${extra_videoed_args}
```

**Comment by lbfs** [comment]
The repository already works under Linux and Windows, I'm very confused....

**Pull request closed without merging**
