### PR TITLE
DockerFile for Mac users to run DeepfaceLab with CPU Mode

### PR DESCRIPTION
**Pull request by Pluckypan**
Make an easy way to run DeepFaceLab in Docker with cpu only mode for **Mac Users**,Check out **DockerCPU.md** for more detailed instructions.

### Fix Some Bugs:
1.  fix localization nullpointer exception [96a5fd0](https://github.com/iperov/DeepFaceLab/commit/96a5fd0f9ff91ed12c7f4cab41394a8ac08993b1)
2.  fix devicelib error line:61  [02f511c](https://github.com/iperov/DeepFaceLab/commit/02f511c50d3139ec5c0e18b027631e5f0809f0f8)

### CODE REVIEW

**Comment by Pluckypan** [comment]
@iperov  All necessary files

**Comment by iperov** [comment]
1) Memory leakage will occur on thread queues if no preview
2) where is tf in requirements-cpu-docker.txt ?

also I cannot support linux scripts in future, because I am not familiar with linux.

**Comment by Pluckypan** [comment]
1. can you fix it.it works for me with no preview.the big problem is it's too slow train with cpu.
2. the `DockerFile.cpu`  has provide tensorflow runtime. `FROM tensorflow/tensorflow:latest-py3`

I think it's useful for MacBook users. Because you just released Windows applications.

**Comment by iperov** [comment]
yes CPU train only good for H64 with 2 batch size.

Latest tf is not good. Repo curently tested only with 1.11.0.

**Comment by iperov** [comment]
May be create separated branch or fork special for mac ? I just dont want to support mac/linux and docker :(

**Comment by Pluckypan** [comment]
ok, it's up to u.thx.

**Comment by Pluckypan** [comment]
@iperov   Better not,because I haven't test it.
But i think you can edit `FROM tensorflow/tensorflow:latest-py3` to `FROM tensorflow/tensorflow:1.11.0-py3` in `Dockerfile.cpu` if `DeepFaceLab`  better run with `tensorflow:1.11.0`.

**Comment by iperov** [comment]
ok

**Comment by Tsumib** [comment]
Hi, for some reason I'm not able to clone:
git git@github.com:iperov/DeepFaceLab.git
Terminal says:
git: 'git@github.com:iperov/DeepFaceLab.git' is not a git command. See 'git --help'.
Therefore I don't have the "requirements-cpu-docker.txt" file. I tried to clone the DeepLabFace master and use the requirements-cpu.txt instead (changed in the container as well). But when I try to mount DeepFaceLab volume, terminal trow me this:
docker: Error response from daemon: Conflict. The container name "/deepfacelab-cpu" is already in use by container "ec525e8ec6fdf06d7c203d6137a03217fa394722bcf13d7fda8883d4c91b9279". You have to remove (or rename) that container to be able to reuse that name.
Any help or insight will be great, thks

**Pull request merged**
