### PR TITLE
Fixes missing predicted src mask in 'SAEHD masked' preview

### PR DESCRIPTION
**Pull request by jmhummel**
Fixes a bug where the predicted source images are missing masks in the 'SAEHD masked' preview
- Updated `AE_view` function to include predicted source masks `pred_src_srcm`
- Updated `onGetPreview` function to set `SSM` masks returned from `AE_view` and apply them to the predicted source for 'SAEHD masked'

Example of bug:
preview_image_bug

Demonstration of fix:
preview_image_fix

### CODE REVIEW

**Comment by Cioscos** [comment]
Actually it isn't a bug.

**Comment by jmhummel** [comment]
> Actually it isn't a bug.

How so?

**Comment by Cioscos** [comment]
> > Actually it isn't a bug.
> 
> How so?

This is not a bug. Just mask tracking for src predict is unnecessary.

**Comment by jmhummel** [comment]
> This is not a bug. Just mask tracking for src predict is unnecessary.

We have a "SAEHD Masked" preview screen, there's no reason we shouldn't follow the exact same conventions for the `pred-src` previews as the `pred-dst `previews.

I would also argue, the `pred-src` masks ARE important, and more-so then the `pred-dst` masks, they follow the exact same path through the model as the masks for our final `pred-src-dst` output. This preview screen can be a useful tool for validating that the `pred-src` masks are training properly.

You may argue that this issue is low priority, it's just a small cosmetic issue, but this is most certainly a bug. The fix is trivial and has no risk of impacting users reliant on current behavior.

**Comment by iperov** [comment]
that is not a bug.

**Comment by jmhummel** [comment]
Could you please explain why this isn't a bug @iperov ?

**Pull request closed without merging**
