### PR TITLE
fix #581

### LINKED ISSUE #581: Can't override model trainer settings in Ubuntu
With Ubuntu, when pressing Enter at the option to override settings before training the program skips user input and begins training with the first run settings instead.  Windows release seems to work fine though.

### PR DESCRIPTION
**Pull request by orkblutt**
fix issue loosing stdin in Linux

### CODE REVIEW

**Comment by iperov** [comment]
Colab is Linux and all works fine.
Why to change that?

**Comment by orkblutt** [comment]
Not working on Ubuntu/Debian ...

**Comment by iperov** [comment]
this fix may impact windows or colab

**Comment by orkblutt** [comment]
No impact on Windows. I do not tested on Colab but it should work too

**Comment by iperov** [comment]
dup's may caus of descriptors leakage

**Comment by iperov** [comment]
try
```
p = multiprocessing.Process(target=self.input_process, args=( os.dup(sys.stdin.fileno()), sq, str))
```

**Comment by orkblutt** [comment]
yes you're right... i used dup at the wrong place. I will test it this night and give you the result

**Comment by TooMuchFun** [comment]
give more context about what is broken and how to repro

**Comment by orkblutt** [comment]
hi Iperov,

I tested your code but it does not fixe the issue. It looks to be the more logical place to dup the stdin fd but it's not working. My fix is resolving the issue (I seen 2 or 3 issues related to this problem than could be closed using this fix.
btw, very happy to see you back after 2 weeks of vacation ?

regards,

orkblutt

**Comment by iperov** [comment]
there are no issues in windows or colab.
I will not add more bugs by your pr

**Comment by orkblutt** [comment]
So you finally introduced my new bug ?

**Comment by iperov** [comment]
found a better fix for linux

**Pull request closed without merging**
