### PR TITLE
DockerFile for Mac users to run DeepfaceLab with CPU Mode

### PR DESCRIPTION
**Pull request by Pluckypan**
If you just have a MacBook.DeepFaceLab GPU mode does not works. However,it can also works with CPU mode.Use Docker will help you build the DRE (DeepFaceLab Runtime Environment) Easier.Check out [DockerCPU.md](https://github.com/Pluckypan/DeepFaceLab/blob/master/DockerCPU.md) for more detailed instructions.

### Fix Bugs:
1.  fix localization nullpointer exception [44eefb0](https://github.com/iperov/DeepFaceLab/commit/44eefb0727d5647e7c549e97fa97ad642df17619)
2. fix ffmpeg aac exception  [f9d36d2](https://github.com/iperov/DeepFaceLab/commit/f9d36d20403cde364957d0886cc2e0e473718245)
3.  fix devicelib error line:61  [111bced](https://github.com/iperov/DeepFaceLab/commit/111bced890cad1781f38f0c09e4c94600a9a6cbf)

### CODE REVIEW

**Comment by iperov** [comment]
what you did with repo with this commit?

**Comment by iperov** [comment]
14 files changed? no thx

**Comment by iperov** [comment]
can you please fix your PR ? there are too many files changed

**Comment by TooMuchFun** [comment]
@Pluckypan a few suggestions

- To minimize the number of files or lines changed, please go back through your commits and remove all whitespace related changes. These clutter up commit history and make reverting a challenge. 
- Move as many of these files into their own new directory in the repo root. This pull adds a lot of files to the repo root unnecessarily. 
- Please rebase your branch and combine all changes into related commits. This PR adds new features, documentation updates, syntax changes, and bug fixes. Please combine and reduce your commits. I suggest rebase, do not squash and merge.

**Comment by TooMuchFun** [comment]
Also, I have created my own GPU-enabled Dockerfile to add once this has been resolved. I modified this [Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu.Dockerfile) and added steps to install and bootstrap DFL. 

I have tested it on an Ubuntu 16.04 host with a 1070 GTX but I imagine it runs on any platform supporting nvidia-docker.

**Comment by iperov** [comment]
@Pluckypan can you please make PR with change only necessary files?

**Pull request closed without merging**
