### PR TITLE
Update MergeMasked.py

### PR DESCRIPTION
**Pull request by birdstream**
Merger still throws a bunch of errors and glitches on linux when merging using seamless and super resolution.

### CODE REVIEW

**Comment by iperov** [comment]
looks like a shit.
Why should I put nan_to_num after every fucking numpy operation?
fuck linux.
I will remove prev fix too. It is a bunch of shit code.
This is why I don't like linux.

**Comment by iperov** [comment]
if you really want to contribute, investigate initial problem of this bug. I don't like such solution in this PR.

Previous fix is also removed.

**Comment by TalosOfCrete** [comment]
Are you a fucking idiot, iperov?  Put down the vodka and support Linux.  There’s a reason it’s the preferred operating system of just about every deep learning head.  Failure to properly support it will drive Linux users away, which easily makes up at least half of your user base; yes, this includes people running Linux VM’s on Windows because Windows VRAM management is shitty.

I’ve tried to be polite to you on a number of issues, but my points don’t seem to be going through your cinder block of a skull; hence, this time around, I am going to use language that will get your attention, you sentient enema.

Why don’t you fucking test the PR first, or are you too lazy to make a simple Linux VM?  Jesus fucking Christ.

**Comment by TalosOfCrete** [comment]
Ban me if you want.  It’ll only make you look like more of an asshole, and you will be hemorrhaging developers faster than you can say “how much you donate for this feature”.

**Comment by iperov** [comment]
> which easily makes up at least half of your user base

are you kidding? linux users 0.0001%
most users from windows.
Linux is for retards.

**Comment by birdstream** [comment]
I won't question your decision not to merge or even test this PR, it's your code! But 3 instances hardly qualify as "every fucking numpy operation" does it?

I get it, you won't support Linux. Fine!

Also, I do agree that it is dirty workaround code. But then why did you merge Ilya's PR in the first place? The very least we could ask for is you being consistent.

Thank You

**Comment by iperov** [comment]
> But then why did you merge Ilya's PR in the first place? 

already removed the code.
Such fix is not acceptable anyway.
The problem has to be investigated from the root.

**Comment by Romejanic** [comment]
> Linux is for retards.

Are.. are you a twelve year old?

**Pull request closed without merging**
