### PR TITLE
Fix bug in umeyama + refactoring

### PR DESCRIPTION
**Pull request by kcimit**
Fixes bug refferred here https://github.com/scikit-image/scikit-image/commit/e20a844ed03c7001a30a5a74dc98a26212b6fdf6#diff-e25df02d1283e21afd670d5a442e4bbf

Dot product operand is also replaced

### CODE REVIEW

**Comment by iperov** [comment]
stop pr

**Comment by iperov** [comment]
what the bug in umeyama?
have you before/after comparison?

**Comment by kcimit** [comment]
As I mentioned this bug reported in original source https://github.com/scikit-image/scikit-image/commit/e20a844ed03c7001a30a5a74dc98a26212b6fdf6#diff-e25df02d1283e21afd670d5a442e4bbf
In manual extract I have difficulties with side profile faces since some faces were flipped - it is rare but happens sometime, probably landmarks rect is not correctly oriented. With that fix I don't have any more such difficulties.
On 24.10.2019 10:43:52, iperov <notifications@github.com> wrote:
what the bug in umeyama?
have you before/after comparison?

**Comment by iperov** [comment]
and what about operation order?

```
U @ np.diag(d) @ V
```

vs

```
np.dot(U, np.dot(np.diag(d), V))
```

**Comment by kcimit** [comment]
Good question - but I don't see difference in reality.
Here is an example:
Source:
0001_source

Current implementation:
0001_current

Fixed:
0001_fixed

**Comment by iperov** [comment]
really fixed the problem
thx

**Comment by iperov** [comment]
but I prefer to use np.dot as more readable and understable version

**Comment by iperov** [comment]
Before https://i.imgur.com/pEoZ6Mu.mp4
after https://i.imgur.com/wO2Guo7.mp4

**Comment by kcimit** [comment]
yes, looks quite stable
On 24.10.2019 19:47:26, iperov <notifications@github.com> wrote:
Before https://i.imgur.com/pEoZ6Mu.mp4 [https://i.imgur.com/pEoZ6Mu.mp4]
after https://i.imgur.com/wO2Guo7.mp4 [https://i.imgur.com/wO2Guo7.mp4]

**Pull request closed without merging**
